### ISSUE TITLE
crawling fails if subfolders are present

### ISSUE THREAD

**Issue by crazdrama** [sanjit-sinha/bhadoo-index-scraper#3]
crawling fails if index link has subfolders...can you help figure this out pls

**Comment by AvAkanksh** [comment]
it easy just check the code, he has ignored if there is a subfolder so just modify the code remove the if condition then 
Change this :
	        
                 if files_type == "application/vnd.google-apps.folder": pass
	        else:
	            direct_download_link = url + urllib.parse.quote(files_name)
	            result += f"• {files_name}:-\n{direct_download_link}\n\n"

to :

	        direct_download_link = url + urllib.parse.quote(files_name)
	        result += f"• {files_name}:-\n{direct_download_link}\n\n"

then you are good to go.

**Comment by crazdrama** [comment]
> it easy just check the code, he has ignored if there is a subfolder so just modify the code remove the if condition then Change this :
> 
> ```
>              if files_type == "application/vnd.google-apps.folder": pass
>         else:
>             direct_download_link = url + urllib.parse.quote(files_name)
>             result += f"• {files_name}:-\n{direct_download_link}\n\n"
> ```
> 
> to :
> 
> ```
>         direct_download_link = url + urllib.parse.quote(files_name)
>         result += f"• {files_name}:-\n{direct_download_link}\n\n"
> ```
> 
> then you are good to go.

i did change the script like u mentioned but it only displays the link to the subfolder and not the contents of the subfolder...cud u take a look at it again??

**Comment by kuesttman** [comment]
Indeed, it would be interesting if the script could go through the subfolders and capture the file links of the subfolders. A depth to be reached from subfolders could be defined. If I want the script to capture subfolder links for up to 1 or 2 sublevels. It could be configured.

**Comment by erickyun** [comment]
> it easy just check the code, he has ignored if there is a subfolder so just modify the code remove the if condition then Change this :
> 
> ```
>              if files_type == "application/vnd.google-apps.folder": pass
>         else:
>             direct_download_link = url + urllib.parse.quote(files_name)
>             result += f"• {files_name}:-\n{direct_download_link}\n\n"
> ```
> 
> to :
> 
> ```
>         direct_download_link = url + urllib.parse.quote(files_name)
>         result += f"• {files_name}:-\n{direct_download_link}\n\n"
> ```

I'm getting an `IndentationError` could you please help me sir?
