### ISSUE TITLE
Just wanted to talk to you about ur code

### ISSUE THREAD

**Issue by AvAkanksh** [sanjit-sinha/bhadoo-index-scraper#4]
Hey Hello @sanjit-sinha , i am @AvAkanksh I just wanted to know how you got the idea to write a web scrapping code all by your self. I understood your code, but i wonder how you got to know which parameters are required to make the prefect request. can you please explain the methodology behind it. i know that authentication code is required i got that by checking out the network response. But i am not sure how you came up with the page_token and page_index, so can you please please please please please explain how you got to know they needed to be present.

Thank you in advance.

Also i would like to have conversation in private about other stuff related to web scrapping and other stuff if you have the time to spare. Thank you.

you can also make some modifications to the code so we can directly get the download link of the content present which are there in the subfolders too. That would be too helpful to others .

Thank you once again. 

Edited:

I have understood how u got to know why u have used page_token and page_index i have checked the networks tab and checked the post tab so i found the required data to make the post. but i still don't understand how you got the idea to reverse the string and then decode it using the base64. If you just say that it would be helpful for me in future. 

Thank you

**Comment by sanjit-sinha** [comment]
Hey avinash. 
can we move this convo to somewhere else? This doesn't feel like right place to discuss. I dropped a mail at your gmail wich is mentioned in your profile.

And about that subfolder thingy i intentionally kept it that way.
As some folder have hundreds of subfolder and again inside those subfolder can have x amount have subfolder(s).

So scraping them lead to request spam in worker link and make script unstable.

So i excluded subfolder scraping and made that script simple.
