### ISSUE TITLE
can we get ddl links only without filenames?

### ISSUE THREAD

**Issue by askfriends** [sanjit-sinha/bhadoo-index-scraper#7]
can we get ddl links only without filenames? that would be handy.
thanks

**Comment by pingu6** [comment]
just edit this line https://github.com/sanjit-sinha/Bhadoo-Index-Scraper/blob/main/Index-scraper.py#L57
to something like this:
```py
result += f"{direct_download_link}\n"
```

**Comment by askfriends** [comment]
> ```python
> result += f"{direct_download_link}\n"
> ```

yeah thanks it works.

**Comment by pingu6** [comment]
what's your usecase?
i use this for aria2
and i was think to fork this repo and add option to output to file and things like that

**Comment by askfriends** [comment]
> what's your usecase? i use this for aria2 and i was think to fork this repo and add option to output to file and things like that

i will get download links only so i can further process them in bot or jdownloader directly without copy pasting each link.

**Comment by crackerbad** [comment]
> what's your usecase? i use this for aria2 and i was think to fork this repo and add option to output to file and things like that



> > what's your usecase? i use this for aria2 and i was think to fork this repo and add option to output to file and things like that
> 
> i will get download links only so i can further process them in bot or jdownloader directly without copy pasting each link.

I have made a fork where I modified it to turn it into a downloader. If you are interested in using it or providing suggestions, please let me know.

https://github.com/crackerbad/Bhadoo-Index-Downloader
