### ISSUE TITLE
Not working with direct-link disabled feature

### ISSUE THREAD

**Issue by askfriends** [sanjit-sinha/bhadoo-index-scraper#9]
Can you bypass direct-link disable feature?
Bhaddoo has now added this feature to prevent direct links, which means ur script cant scrap such indexes.
So please fix it or add some bypass mechanism
Example: https://blast.ola-movies.workers.dev/
username :- GLOBAL
PASS :- OLABREAKERS

**Comment by crackerbad** [comment]
It doesn't work if you use secondary domain too.

**Comment by askfriends** [comment]
> It doesn't work if you use secondary domain too.

yeah so any work around?

**Comment by crackerbad** [comment]
> > It doesn't work if you use secondary domain too.
> 
> yeah so any work around?

"Not for now, as the code combines the index URL and the filename. I would have to find a way to capture the link of the secondary domain."

**Comment by askfriends** [comment]
> > > It doesn't work if you use secondary domain too.
> > 
> > 
> > yeah so any work around?
> 
> "Not for now, as the code combines the index URL and the filename. I would have to find a way to capture the link of the secondary domain."

waiting for next major UPDATE!

**Comment by crackerbad** [comment]
> > > > It doesn't work if you use secondary domain too.
> > > 
> > > 
> > > yeah so any work around?
> > 
> > 
> > "Not for now, as the code combines the index URL and the filename. I would have to find a way to capture the link of the secondary domain."
> 
> waiting for next major UPDATE!

I made a pull request to bypass the direct link protection. https://github.com/sanjit-sinha/Bhadoo-Index-Scraper/pull/11

**Comment by askfriends** [comment]
> > > > > It doesn't work if you use secondary domain too.
> > > > 
> > > > 
> > > > yeah so any work around?
> > > 
> > > 
> > > "Not for now, as the code combines the index URL and the filename. I would have to find a way to capture the link of the secondary domain."
> > 
> > 
> > waiting for next major UPDATE!
> 
> I made a pull request to bypass the direct link protection. #11

cant wait to put my hands on this major update.

**Comment by sanjit-sinha** [comment]
Thanks for the PR
